services:
  app:
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API=$REACT_APP_API
    build: 
      context: .
      dockerfile: Dockerfile
    expose:
      - 3000
    volumes:
      - './src:/app/src'